
import turtle
s = turtle.getscreen()
t = turtle.Turtle()
turtle.bgcolor("lightblue")
t.shape("circle")
t.fillcolor("lightblue")
t.speed(10)

t.penup()
t.goto(-760,50)
t.pendown()
t.begin_fill()
t.color("brown")
for i in range(3):
    t.forward(400)
    t.left(120)
t.end_fill()

t.penup()
t.goto(-370,50)
t.pendown()
t.begin_fill()
t.color("brown")
for i in range(3):
    t.forward(400)
    t.left(120)
t.end_fill()


t.penup()
t.goto(-10,50)
t.pendown()
t.begin_fill()
t.color("brown")
for i in range(3):
    t.forward(400)
    t.left(120)
t.end_fill()

t.penup()
t.goto(360,50)
t.pendown()
t.begin_fill()
t.color("brown")
for i in range(3):
    t.forward(400)
    t.left(120)
t.end_fill()


t.penup()
t.goto(10,250)
t.pendown()
t.begin_fill()
t.color("yellow")
t.circle(50)
t.penup()
t.end_fill()

t.penup()
t.goto(10, 300)
for i in range(8):
        t.pendown()
        t.pensize(5)
        t.forward(100)
        t.backward(100)
        t.left(45)
        t.penup()

t.penup()
t.goto(-120, 50)
t.pendown()
t.begin_fill()
t.color("royal blue")
t.right(90)
t.forward(500)
t.left(90)
t.forward(300)
t.left(90)
t.forward(500)
t.end_fill()
t.hideturtle()

t.penup()
t.goto(755,-300)
t.pendown()
t.begin_fill()
t.color("green")
t.left(90)
t.forward(1550)
t.backward(1550)
t.left(90)
t.forward(90)
t.right(90)
t.forward(1550)
t.right(90)
t.forward(90)
t.end_fill()

t.penup()
t.goto(-400,-200) 
t.pendown()
t.begin_fill()
t.color("green")
t.left(90)
t.forward(200)
t.right(120)
t.forward(200)
t.end_fill()
  
t.penup()
t.goto(-470,-200)
t.pendown()
t.begin_fill()
t.color("brown")
t.right(150)
t.forward(100)
t.right(90)
t.forward(60)
t.right(90)
t.forward(100)
t.end_fill()

t.penup()
t.goto(500,-150) 
t.pendown()
t.begin_fill()
t.color("hotpink1")
t.left(90)
t.forward(130)
t.right(120)
t.forward(130)
t.end_fill()

t.penup()
t.goto(500, -150)
t.pendown()
t.begin_fill()
t.color("darkorchid3")
t.right(150)
t.forward(150)
t.right(90)
t.forward(130)
t.right(90)
t.forward(150)
t.end_fill()



t.penup()
t.goto(420, -220)
t.pendown()
t.begin_fill()
t.color("indianred3")
t.right(90)
t.forward(40)
t.right(90)
t.forward(80)
t.right(90)
t.forward(40)
t.right(90)
t.forward(80)
t.end_fill()


turtle.mainloop()